server:
  port: 8081

coingecko:
  api:
    key:  CG-7QPJ7ScyM3LgSh3vWQG4Wm8K
    base:  https://api.coingecko.com/api/v3

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cryptostream
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true