server:
  port: 8082

coingecko:
  api:
    key:  
    base:  https://api.coingecko.com/api/v3

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptostream
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer