server:
  port: 8082

coingecko:
  api:
    key:  CG-7QPJ7ScyM3LgSh3vWQG4Wm8K
    base:  https://api.coingecko.com/api/v3

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cryptostream
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer