services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"  # Puerto para conexiones externas
      - "9093:9093"  # Puerto para conexiones internas
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Asegúrate de que esto esté configurado
    networks:
      - cryptostream_network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - cryptostream_network

networks:
  cryptostream_network:
    name: cryptostream_network
    driver: bridge
    external: true